name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout репозитория
      uses: actions/checkout@v3

    - name: Установка Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Установка зависимостей
      run: pip install keyboard pyperclip

    - name: Установка PyInstaller
      run: pip install pyinstaller

    - name: Сборка EXE через PyInstaller
      run: |
        pyinstaller punto_switcher_clone.spec

    - name: Проверка содержимого dist
      run: Get-ChildItem -Recurse -Path dist

    - name: Архивировать всё содержимое dist
      run: Compress-Archive -Path dist\* -DestinationPath punto_switcher_clone.zip

    - name: Финальная проверка
      run: Get-ChildItem -Path dist

    - name: Upload EXE напрямую
      uses: actions/upload-artifact@v3
      with:
        name: punto_switcher_clone_exe
        path: dist/punto_switcher_clone.exe    
